name: example
description: FAB Circular Menu Example

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fab_circular_menu:
    path: ./../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
